# Generated by Django 5.1.1 on 2024-10-16 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketApp', '0002_alter_usuarios_empresa_alter_usuarios_grupo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='empresa',
        ),
        migrations.AddField(
            model_name='usuarios',
            name='empresa',
            field=models.ManyToManyField(blank=True, related_name='usuarios', to='ticketApp.empresas'),
        ),
    ]
