# Generated by Django 5.1.1 on 2024-10-31 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketApp', '0002_notafiscal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notafiscal',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nf', to='ticketApp.tickets'),
        ),
    ]
