# Generated by Django 5.1.1 on 2024-11-01 20:06

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketApp', '0003_alter_notafiscal_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagens',
            name='pdf',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='pdf'),
        ),
        migrations.AlterField(
            model_name='imagens',
            name='imagem',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='imagem'),
        ),
        migrations.AlterField(
            model_name='notafiscal',
            name='arquivo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='arquivo'),
        ),
    ]
