# Generated by Django 5.1.1 on 2024-10-21 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketApp', '0003_remove_usuarios_empresa_usuarios_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagens',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='imagens_tickets/'),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='criacao',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
