# Generated by Django 5.1.1 on 2024-11-04 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketApp', '0004_imagens_pdf_alter_imagens_imagem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='criacao',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
