# Generated by Django 5.1.1 on 2024-10-21 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketApp', '0004_alter_imagens_imagem_alter_tickets_criacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='criacao',
            field=models.DateField(auto_now_add=True),
        ),
    ]
