# Generated by Django 5.1.1 on 2024-11-04 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketApp', '0005_alter_tickets_criacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='horario',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='criacao',
            field=models.DateField(auto_now_add=True),
        ),
    ]
